version: '3.9'

services:
  redis:
    image: redis:7-alpine
    container_name: mercurius-redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'no']

  mercurius-worker:
    build: .
    container_name: mercurius-worker
    depends_on:
      - redis
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - WEBHOOK_QUEUE_NAME=mercurius_webhooks
      - WEBHOOK_DLQ_NAME=mercurius_webhooks_dlq
    restart: unless-stopped


